#!/bin/sh
#
# PROVIDE: inotif
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name=inotif
rcvar=inotif_enable

command="/usr/local/bin/inotif"

load_rc_config $name

#
# DO NOT CHANGE THESE DEFAULT VALUES HERE
# SET THEM IN THE /etc/rc.conf FILE
#
utility_enable=${utility_enable-"NO"}
pidfile=${utility_pidfile-"/var/run/inotif.pid"}

run_rc_command "$1"