#!/bin/sh
#
# PROVIDE: inotif
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name=inotif
rcvar=inotif_enable

inotif_user="inotif"
command="/usr/local/bin/inotif"

pidfile="/var/run/inotif.pid"

load_rc_config $name
run_rc_command "$1"