#!/bin/sh
PATH="/sbin:/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/bin:/usr/bin"
set -x
exit1() {
	echo "FAIL"
 	echo "$1"
 	exit 1;
}

# Load inotif configuration
if [ -f /etc/inotif.conf ]; then
    CONF="/etc/inotif.conf"
elif [ -f conf/inotif.conf ]; then
    CONF="conf/inotif.conf"
else
    exit1 "can't found inotif.conf"
fi
. $CONF
user=$(whoami)
home=$(getent passwd $user | cut -d: -f6)
branch="$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | head -n1)" > /dev/null 2>&1

# Clear variable to avoid cache.
check_repo='' && dir_list=''
dir_list="$dir_default $(curl -s $consul_address/v1/kv/inotif/$branch?raw | jq .dir[] | sed "s/\"/ /g")"
check_repo="$(curl -s $consul_address/v1/kv/inotif/config?raw | jq .repo_url | sed "s/\"/ /g")"
if [ ! -z "$check_repo" ]; then
	repo_url="$check_repo"
fi

# Setup git init.
setup_repo(){
	git checkout -B $branch > /dev/null 2>&1
	git remote add origin $repo_url > /dev/null 2>&1 || git remote set-url origin $repo_url > /dev/null 2>&1
	for dir_name in $dir_list; do		
		if [ -d "$home/.inotif"$dir_name"" ] || mkdir -p "$home/.inotif"$dir_name""; then
			# Rsync required folder that max size 1MB, and don't forget to exclude git config.
		    rsync -aq --delete --max-size=1.0m --exclude=.git* --exclude=.git "$dir_name"/ $home/.inotif"$dir_name"/ > /dev/null 2>&1
		fi
	done
	git config user.name $user
	git config user.email $user@$branch
	if [ -n "$(git status --porcelain)" ]; then
		git add -A > /dev/null 2>&1
		git commit -m "auto commit" > /dev/null 2>&1
		git push origin $branch
		echo "Pushed" $dir_list
	else 
	 	echo "Nothing to commit";
	fi
}

# Create inotif directory if doesn't exist.
# This directory will be used to store the monitored file or directory.
[-d $home/.inotif ] mkdir -p $home/.inotif

# Change to inotif directory.
cd $home/.inotif
# Just updating git repository if git already installed.
# or reinit git when git not installed.
if [ -d "$home/.inotif/.git" ]; then
	# Only pull specific branch from repository.
	git pull origin $branch > /dev/null 2>&1
	git stash > /dev/null 2>&1
	# Doing setup repo
	setup_repo
else
	rm -rf $home/.inotif/* 
	# Clone if remote repository already stored.
	git clone -b $branch $repo_url ./ > /dev/null 2>&1 
	if [ $? -eq 0 ]; then
		# Doing setup repo
		setup_repo
	else
		# Init git if on repository doesn't exists.
		git init > /dev/null 2>&1
		# Doing setup repo
		setup_repo
	fi
fi
