---
- name: Update apt
  apt: update_cache=yes

# Install package supervisor
- name: Install supervisor
  apt: name=supervisor state=latest

- name: Set up inotif conf
  copy: src=../conf/supervisord.conf dest=/etc/supervisor/conf.d/inotif.conf

- name: Reread supervisor
  command: supervisorctl reread

- name: Update supervisor
  command: supervisorctl update