---
- name: Install package sysutils/py-supervisor
  portinstall:
    name: sysutils/py-supervisor
    state: present

- name: Transfer the supervisord.conf conf
  copy: src=../conf/supervisord.conf dest=/usr/local/etc/supervisord.ini

- name: Add a line to supervisord.conf if it does not exist
  blockinfile: 
    dest: /usr/local/etc/supervisord.conf
    block: |
      [include] 
      files = /usr/local/etc/supervisord.ini

- name: Append `supervisord_enable="YES"` if it not exist.
  lineinfile:
    dest: /etc/rc.conf
    line: 'supervisord_enable="YES"'

- name: Append `inotif_enable="YES"` if it not exist.
  lineinfile:
    dest: /etc/rc.conf
    line: 'inotif_enable="YES"'

- name: start supervisord
  service: name=supervisord state=restarted