---
- hosts: ubuntu
  remote_user: ubuntu
  become: true
  vars:
     basic_packages: [ 'jq', 'git', 'rsync', 'curl' ]
     supervisor_conf: "/etc/supervisor/conf.d/"
  tasks:
    - name: Create user inotif
      user: name=inotif shell=/bin/sh

    - name: Install basic packages
      package: name={{ item }} state=latest
      with_items: basic_packages

    - include: Task/FreeBSD-task.yml
      when: ansible_distribution == "FreeBSD"

    - include: Task/Debian-task.yml
      when: (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')

  handlers:
    - name: restart supervisor
      service: name=supervisor state=restarted