---
- hosts: ubuntu
  remote_user: root
  become: true
  vars:
     basic_packages: [ 'jq', 'git', 'rsync', 'curl' ]
     supervisor_conf: "/etc/supervisor/conf.d/"
  tasks:
    - name: Create user inotif
      user: name=inotif shell=/bin/sh

    - name: Install basic packages
      package: name={{ item }} state=latest
      with_items: basic_packages

    - name: Copy inotif executable file to /usr/local/bin/
      copy: src=../inotif dest="/usr/local/bin/inotif" mode=a+x

    - name: Copy config inotif to /etc/
      copy: src=../conf/inotif.conf dest="/etc/"

    - name: Create file output log
      copy:
        content: ""
        dest: /var/log/inotif.log
        force: no
        mode: 0666

    - name: Create file output err
      copy:
        content: ""
        dest: /var/log/inotif.err
        force: no
        mode: 0666

    - include: Task/FreeBSD-task.yml
      when: ansible_distribution == "FreeBSD"

    - include: Task/Debian-task.yml
      when: (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')

  handlers:
    - name: restart supervisor
      service: name=supervisor state=restarted