---
- hosts: all
  remote_user: root
  become: yes
  vars:
     basic_packages: [ 'jq', 'rsync', 'git', 'curl' ]
  tasks:
    - name: Create user inotif
      user: name=inotif shell=/bin/sh

    - name: Install debian7 requirement
      include: Task/debian7-requirement.yml
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'

    - name: Install debian8 requirement
      include: Task/debian8-requirement.yml
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'

    - name: Install basic packages
      package: name={{ item }} state=latest
      with_items: basic_packages

    - name: Copy inotif executable file to /usr/local/bin/
      copy: src=../inotif dest="/usr/local/bin/inotif" mode=0777

    - name: Copy config inotif to /etc/
      copy: src=../conf/inotif.conf dest="/etc/"

    - include: Task/FreeBSD-task.yml
      when: ansible_distribution == "FreeBSD"

    - include: Task/Debian-task.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    
    - name: Restart supervisorctl
      supervisorctl:
        name: inotif
        state: restarted
