---
- hosts: all
  remote_user: root
  become: yes
  vars:
     basic_packages: [ 'jq', 'rsync', 'git', 'curl' ]
  tasks:
    - name: Create user inotif
      user: name=inotif shell=/bin/sh

    - name: Install basic packages
      package: name={{ item }} state=present
      with_items: basic_packages

    - name: Copy inotif executable file to /usr/local/bin/
      copy: src=../inotif dest="/usr/local/bin/inotif" mode=0777

    - name: Copy config inotif to /etc/
      copy: src=../conf/inotif.conf dest="/etc/"

    - include: Task/FreeBSD-task.yml
      when: ansible_distribution == "FreeBSD"

    - include: Task/Debian-task.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Reread and add supervisorctl
      supervisorctl:
        name: inotif
        state: present

    - name: Update and restart supervisorctl
      supervisorctl:
        name: inotif
        state: restarted